### ISSUE TITLE
Issue with keyboard

### ISSUE THREAD

**Issue by w3ggy** [underdog-tech/pinwheel-flutter-sdk#4]
When the keyboard is opened the buttons overlap the input field and the user has to manually scroll down.

<details>

![image](https://user-images.githubusercontent.com/12301508/130453098-d2dcfcaf-6500-46d9-abd3-f5463989802f.png)

</details>

The problem occurs on both platforms with the latest version in the `main` branch.

**Comment by rawbee** [comment]
Thanks for the report, I am taking a closer look at this.

**Comment by rawbee** [comment]
fixed with 2.3.3
